In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [3]:
x = np.identity(5)
x[0]

array([ 1.,  0.,  0.,  0.,  0.])

In [4]:
x[0].shape

(5,)

In [5]:
x[0].T

array([ 1.,  0.,  0.,  0.,  0.])